server {
	listen 8080;

	add_header Access-Control-Allow-Origin * always;

	location ~ ^/(style\.json|fonts/|sprites/) {
		add_header Cache-Control "public, max-age=3600";
		root /data;
	}

	location / {
		proxy_pass http://pmtiles-internal:8080;
		proxy_set_header Host $host;
	}
}
